#!/bin/bash

dir=`mktemp -d`

if [ -z "$3" ] ; then 
    echo usage: $0 fps output file1 file2 file3 ...
    exit 1
fi

fps=${1}
output=${2}

output_framerate=40 # this needs to be faster than 25fps for crazyquick animations
output_codec="h263" # all Android devices support h263
output_size="352x288" # 3gp only supports a few weird sizes. This is one of them.
output_quality="512k" # this has been tuned by hand. in units b/s

# i counts through arguments, j increments file names
i=0
j=1
for var in "$@" ; do
    if [ $i -gt 1 ]; then
        # leading 0's
        suf=$(printf "%03d" "$j")

        cp ${var} ${dir}/image_${suf}.jpg
        let j=j+1
    fi
    let i=i+1
done

# with ffmpeg, the output framerate is fixed but the input framerate controls
# how quickly the frames are animated.
ffmpeg -y -r ${fps} -i ${dir}/"image_%03d".jpg -s ${output_size} -r ${output_framerate} -vcodec ${output_codec} -b ${output_quality} ${output}

rm -rf ${dir}
