#!/bin/bash

dir=`mktemp -d`

if [ -z "$1" ] ; then 
    echo usage: $0 output file1 file2 file3 ...
    exit
fi

i=0
for var in "$@" ; do
    if [ $i -gt 1 ]; then
        cp ${var} ${dir}/image${i}.jpg
    fi
    let i=i+1
done

convert -delay 100 -loop 0 -layers Optimize -resize 640x480 ${dir}/image*.jpg $1

