#!/bin/bash

dir=`mktemp -d`

if [ -z "$3" ] ; then 
    echo usage: $0 delay output file1 file2 file3 ...
    exit
fi

# i counts through arguments, j increments file names
i=0
j=1
for var in "$@" ; do
    if [ $i -gt 1 ]; then
        # leading 0's
        suf=$(printf "%03d" "$j")

        cp ${var} ${dir}/image_${suf}.jpg
        let j=j+1
    fi
    let i=i+1
done

convert -delay $1 -loop 0 -layers Optimize -resize 640x480 ${dir}/image*.jpg $2

rm -rf ${dir}
